Repository Leets-Official/Commitato-BE, pull requests merged in 2025-02, with the labels that each got.

#44 refactor: GitHub API 통신 방식 변경
  .github/ISSUE_TEMPLATE/feature.md
  src/main/java/com/leets/commitatobe/domain/commit/controller/CommitController.java
  src/main/java/com/leets/commitatobe/domain/commit/service/FetchCommits.java
  src/main/java/com/leets/commitatobe/domain/commit/service/FetchCommitsTest.java
  src/main/java/com/leets/commitatobe/domain/commit/service/GitHubService.java
  src/main/resources/application-dev.yaml
  src/main/resources/application-prod.yaml
Labels: chore, refactor, style

#46 refactor: GitHub OAuth 방식 변경
  src/main/java/com/leets/commitatobe/domain/commit/service/GitHubService.java
  src/main/java/com/leets/commitatobe/domain/login/service/LoginCommandService.java
  src/main/resources/application-dev.yaml
  src/main/resources/application-local.yaml
  src/main/resources/application-prod.yaml
Labels: chore, refactor

#49 refactor: GitHub OAuth 방식 롤백
  src/main/java/com/leets/commitatobe/domain/commit/service/GitHubService.java
  src/main/java/com/leets/commitatobe/domain/login/service/LoginCommandService.java
  src/main/resources/application-dev.yaml
  src/main/resources/application-local.yaml
  src/main/resources/application-prod.yaml
Labels: chore, refactor

#50 bug: 경험치 최신화 시 정확하게 값이 계산되지 않는 문제 해결
  src/main/java/com/leets/commitatobe/domain/commit/service/GitHubService.java
  src/main/java/com/leets/commitatobe/global/jwt/dto/JwtResponse.java
  src/main/java/com/leets/commitatobe/global/jwt/provider/JwtProvider.java
Labels: bug, refactor
