Repository Leets-Official/Commitato-BE, pull requests merged in 2025-07, with the labels that each got.

#93 refactor: 랭킹 필드 재구현 및 랭킹 조회 로직 수정
  src/main/java/com/leets/commitatobe/CommitatoBeApplication.java
  src/main/java/com/leets/commitatobe/domain/commit/dto/response/CommitResponse.java
  src/main/java/com/leets/commitatobe/domain/user/domain/User.java
  src/main/java/com/leets/commitatobe/domain/user/domain/UserDocument.java
  src/main/java/com/leets/commitatobe/domain/user/dto/response/UserInfoResponse.java
  src/main/java/com/leets/commitatobe/domain/user/dto/response/UserSearchResponse.java
  src/main/java/com/leets/commitatobe/domain/user/service/RankingScheduler.java
  src/main/java/com/leets/commitatobe/domain/user/service/UserQueryService.java
Labels: refactor

#95 bug: 오늘 커밋 횟수가 정상적으로 반환되지 않는 오류
  src/main/java/com/leets/commitatobe/domain/commit/controller/CommitController.java
  src/main/java/com/leets/commitatobe/domain/commit/service/ExpService.java
  src/main/java/com/leets/commitatobe/domain/commit/service/FetchCommitsTest.java
Labels: bug

#97 feat: 커밋 기록 자동 업데이트 스케줄러 구현 및 커밋 기록 카운트 오류 수정
  src/main/java/com/leets/commitatobe/domain/commit/service/DailyCommitScheduler.java
  src/main/java/com/leets/commitatobe/domain/commit/service/ExpService.java
  src/main/java/com/leets/commitatobe/domain/commit/service/FetchCommits.java
Labels: bug, feature

#99 refactor: 주소 이전에 따른 CORS 설정 변경
  src/main/java/com/leets/commitatobe/global/config/SecurityConfig.java
  src/main/resources/application-prod.yaml
Labels: refactor
