Repository Leets-Official/Commitato-BE, pull requests merged in 2025-04, with the labels that each got.

#69 bug: 배포환경에서 ElasticSearch가 연결되지 않는 오류 수정
  src/main/java/com/leets/commitatobe/global/config/elastic/ElasticSearchConfig.java
  src/main/resources/application-dev.yaml
  src/main/resources/application-local.yaml
  src/main/resources/application-prod.yaml
Labels: bug

#71 refactor: 랭킹 조회 jwt 토큰 인증 제외
  src/main/java/com/leets/commitatobe/global/config/SecurityConfig.java
Labels: refactor

#73 bug: ElasticSearch 7.17.10 버전으로 다운그레이드
  src/main/java/com/leets/commitatobe/global/config/elastic/ElasticSearchConfig.java
  src/main/resources/application-dev.yaml
  src/main/resources/application-local.yaml
  src/main/resources/application-prod.yaml
Labels: bug, chore, refactor

#75 feat: 경험치 입력 시 사용자의 경험치 및 티어를 경험치에 맞게 수정하는 api 구현
  src/main/java/com/leets/commitatobe/domain/commit/controller/ExpAndTierTestController.java
  src/main/java/com/leets/commitatobe/domain/commit/dto/response/ExpAndTierResponse.java
  src/main/java/com/leets/commitatobe/domain/commit/service/ExpService.java
Labels: feature

#77 bug: 배포환경에서 ElasticSearch가 연결되지 않는 오류 수정
  src/main/java/com/leets/commitatobe/global/config/elastic/ElasticSearchConfig.java
  src/main/resources/application-dev.yaml
  src/main/resources/application-local.yaml
  src/main/resources/application-prod.yaml
Labels: bug

#79 bug: 검색 기능 실행 시 NullPointerException이 나오는 오류 해결
  src/main/java/com/leets/commitatobe/domain/user/dto/response/UserSearchResponse.java
Labels: bug, refactor
