Repository Leets-Official/Commitato-BE, pull requests merged in 2025-03, with the labels that each got.

#52 refactor: API 코드 가독성 향상을 위한 코드 수정
  src/main/java/com/leets/commitatobe/domain/commit/service/ExpService.java
  src/main/java/com/leets/commitatobe/domain/login/service/LoginQueryService.java
  src/main/java/com/leets/commitatobe/domain/user/controller/UserController.java
  src/main/java/com/leets/commitatobe/domain/user/service/UserQueryService.java
  src/main/resources/data.sql
Labels: refactor, style

#54 feat: 3개월 간 특정 사용자의 커밋 기록 횟수 반환 API 구현
  .DS_Store
  src/main/java/com/leets/commitatobe/domain/commit/repository/CommitRepository.java
  src/main/java/com/leets/commitatobe/domain/user/controller/UserController.java
  src/main/java/com/leets/commitatobe/domain/user/dto/response/UserCommitResponse.java
  src/main/java/com/leets/commitatobe/domain/user/service/UserQueryService.java
Labels: feature, style

#57 Refactor/#56
  src/main/resources/application-dev.yaml
  src/main/resources/application-prod.yaml
  src/main/resources/data.sql
Labels: refactor

#58 bug: Author가 존재하지 않을 경우 서버 에러가 뜨는 오류 해결
  src/main/java/com/leets/commitatobe/domain/commit/service/GitHubService.java
  src/main/resources/application-dev.yaml
  src/main/resources/application-prod.yaml
Labels: bug, refactor, style

#61 bug: 연속 커밋일수를 제대로 받아오지 않는 오류 해결
  src/main/java/com/leets/commitatobe/domain/commit/domain/Commit.java
  src/main/java/com/leets/commitatobe/domain/commit/service/ExpService.java
Labels: bug, refactor

#64 bug: githubAccessToken을 로그인할 때마다 받아올 수 있도록 수정
  src/main/java/com/leets/commitatobe/domain/user/domain/User.java
  src/main/java/com/leets/commitatobe/global/jwt/service/CustomOAuth2UserService.java
Labels: bug
